---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otus-hw4-vs
spec:
  hosts:
    - '*'
  gateways:
    - otus-hw4-gateway
  http:
    - route:
        - destination:
            host: otus-hw2-service
          weight: 50
        - destination:
            host: otus-hw4-service
          weight: 50