apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-hw2-ingress
  namespace: default
#  annotations:
#    / use the shared ingress-nginx
#    kubernetes.io/ingress.class: "nginx-otus"
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otus-hw2-service
            port:
              number: 8000